name: Bug Report
description: File a bug report to help us improve
title: '[Bug]: '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: version
    attributes:
      label: EliCS Version
      description: What version of EliCS are you using?
      placeholder: e.g., 2.1.1
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of the bug
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: If applicable, provide a minimal code sample that reproduces the issue
      render: typescript

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Browser/Node.js version, OS, etc.
      placeholder: e.g., Chrome 120, Node.js 20, macOS 14

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
